"""Added not null bio

Revision ID: 7320fd217b0e
Revises: d87c0c426f21
Create Date: 2026-05-18 18:04:31.795868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7320fd217b0e'
down_revision: Union[str, Sequence[str], None] = 'd87c0c426f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'bio',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'bio',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
